### ISSUE TITLE
Followed instructions, but this didn't work

### ISSUE THREAD

**Issue by wopsononock** [UMNLibraries/primo-explore-hathitrust-availability#11]
Local dev environment works, but when I install the hathi package in the recommended location and try to view it, it overwrites my view's custom.js.  I tried installing in the dev environment root and calling from there, but that doesn't work either.  Installing through Primo Studio does the same thing. What files does the package need to work and where should they be located relative to existing view code?

**Comment by gpeterso** [comment]
Hi @wopsononock. The [Primo Dev Environment](https://github.com/ExLibrisGroup/primo-explore-devenv) overwrites the `custom.js` file whenever any other JS files exist in the project. Specifically, the `gulp run` task dynamically generates the `custom.js` file by concatenating the following files (in this order):

1. `js/custom.module.js` (if it exists)
2. any remaining `.js` files in the `/js` directory (except custom.js)
3. any `.js` files in the `node_modules` directory that match the following patterns:
    `/node_modules/primo-explore*/js/*.js`
    `/node_modules/primo-explore*/dist/*.js`

(#3 is where the HathiTrust plugin is getting pulled in.)

Similarly, all of the `*.css` files in `/css` get concatenated into `custom1.css`. 

The simplest approach to dealing with this concatenation is to copy all of your existing `custom.js` code into a file named `custom.module.js` file. When the `gulp run` task is running, changes to the `custom.module.js` will be pulled into `custom.js` automatically. (Technically, you call the file whatever you want, as long as it isn't `custom.js`.)

Here's an example: https://github.com/ExLibrisGroup/primo-explore-linked-data-demo/tree/master/js
^ Here, the `custom.js` file really doesn't need to be tracked in the repository at all because it's regenerated every time a new package is built. 

I hope that helps, but let me know if you encounter any other problems.

**Comment by wopsononock** [comment]
Thank you.  This was what I needed.
