### ISSUE TITLE
Adjusting your add-on to be compatible with Angular 1.8 

### ISSUE THREAD

**Issue by nilinatan** [UMNLibraries/primo-explore-hathitrust-availability#17]
We plan to upgrade from Angular 1.6.10 to Angular 1.8 in the Primo/Primo VE November 2022 release.
This upgrade may impact your Angular customizations in Primo and Primo VE, specifically your Primo-Studio add-on.
Please make sure to adjust the customizations accordingly prior to the upgrade to ensure a smooth migration to Angular 1.8.
With the November release we will introduce in Primo Studio only add-ons that are adjustable to the Angular 1.8.

You can read more on this planned upgrade on 
https://knowledge.exlibrisgroup.com/Primo/Product_Materials/Announcements/Preparing_for_the_Upgrade_to_Angular_1.8_in_Primo%2F%2FPrimo_VE
[Adjust your customization code using the Transformer Tool](https://astexplorer.net/)
Check this [YouTube](https://youtu.be/jm2w9ghrzaU) for guidelines
Recent webinars: [EMEA/APAC ](https://youtu.be/aZ8A6aF-cFI)and [Americas/EMEA](https://youtu.be/jm2w9ghrzaU)

Please make sure to upload your adjustable add-on prior to November release 
Primo Product Team

**Comment by gpeterso** [comment]
Hi @nilinatan, 

I'm not aware of any issues that would prevent this plugin from working with AngularJS 1.8.  So far, testing with the `&testAngularCompatibility=true` parameter has not revealed any problems. I may have overlooked something though... Was this issue created for general awareness, or is there a specific problem that requires investigation?

Regarding Primo Studio, please note that we do not maintain the `hathi-trust-availability-studio` npm package. It is based on a private fork that Ex Libris created in order to promote Primo Studio. See issue #13 for more information.

Jeff

**Comment by gpeterso** [comment]
Confirmed that plugin works as expected following November release upgrade. No action needed.
